### ISSUE TITLE
Compiler error on versions > 0.1.1.3

### ISSUE THREAD

**Issue by OscarSouth** [zmactep/hasbolt#10]
I've been getting up and running with hasbolt today (thanks for creating the package by the way) and I've run into an issue which I've been able to solve. I felt that it'd be worth noting here.

If I simply set up the package with hasbolt as a dependency, then the following compiler error will be displayed on running `stack build`:

```
/home/oscarsouth/haskellProjects/theHarmonicAlgorithm/app/Main.hs:10:17: error: Variable not in scope: def :: BoltCfg
   |
10 | defaultConfig = def {user = "neo4j", password = "secret"}
   |                 ^^^


--  While building custom Setup.hs for package theHarmonicAlgorithm-0.1.0.0 using:
      /home/oscarsouth/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_2.0.1.0_ghc-8.2.2 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.0.1.0 build lib:theHarmonicAlgorithm exe:theHarmonicAlgorithm-exe --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
```

If I add the following version (or earlier) of hasbolt as an extra-dep, the project will compile successfully:
```
extra-deps:
- hasbolt-0.1.1.3
```
However, any version of hasbolt above this (or none specified at lts-11.8) will fail to compile and return the above error.

I'm currently working with the version specified above, in order to 'sidestep' this issue.

Hope that this is helpful,
Let me know if you'd like any more info.

Thanks,
Oscar South

**Comment by OscarSouth** [comment]
Quick update here:

by adding `data-default` as a dependency to my  executable and adding `import Data.Default (Default (..))` to the project's `Main.hs`, I'm able to successfully compile with version 0.1.3.0.

**Comment by zmactep** [comment]
Hi, @OscarSouth!

I'm so sorry for the late answer. `Data.Default` is not included to `hasbolt`, аs you can use it with fully custom config without defaults. The same was discussed here: #8 . It seems that I really need to add this to README file.

I am sorry again for the delay. Hope you are happy with `hasbolt` in your projects.
